# Import

In [1]:
import pandas as pd
import numpy as np
import sqlite3

# SQL Query

In [2]:
# Load SQL extension for using magic commands
%load_ext sql

In [9]:
# Connect to the database
db_path = r'F:\For work\Database\kaggle_movie.db'

conn = sqlite3.connect(db_path)

#Query the database to get all data from table 'kaggle_movie'
query = "SELECT * FROM kaggle_movie"

kaggle_movie_df = pd.read_sql(query, conn)

conn.close()

In [10]:
kaggle_movie_df

,movies,year,director,star_1,star_2,star_3,star_4,genre_1,genre_2,genre_3,rating,votes,gross,runtime,description
0,The Hitman's Bodyguard,2017,Patrick Hughes,Ryan Reynolds,Samuel L. Jackson,Gary Oldman,Elodie Yung,Action,Comedy,Crime,6.9,205979,75470000.0,118,"The world's top bodyguard gets a new client, a..."
1,Jurassic Park,1993,Steven Spielberg,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,Action,Adventure,Sci-Fi,8.1,897444,402450000.0,127,A pragmatic paleontologist visiting an almost ...
2,Don't Breathe,2016,Fede Alvarez,Stephen Lang,Jane Levy,Dylan Minnette,Daniel Zovatto,Crime,Horror,Thriller,7.1,237601,89220000.0,88,"Hoping to walk away with a massive fortune, a ..."
3,The Lord of the Rings: The Fellowship of the Ring,2001,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,Action,Adventure,Drama,8.8,1713028,315540000.0,178,A meek Hobbit from the Shire and eight compani...
4,Escape Room,2019,Adam Robitel,Taylor Russell,Logan Miller,Jay Ellis,Tyler Labine,Action,Adventure,Horror,6.4,99351,57010000.0,99,Six strangers find themselves in a maze of dea...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,Louder Than a Bomb,2010,"Greg Jacobs, Jon Siskel",Kevin Coval,Adam Gottlieb,Elizabeth Graf,Kevin Harris,Documentary,None,None,7.5,373,40000.0,99,"By turns hopeful and heartbreaking, Louder Tha..."
440,Vidal Sassoon: The Movie,2010,Craig Teper,Beverly Adams,Elgin Charles,Grace Coddington,Michael Gordon,Documentary,None,None,6.5,245,90000.0,90,Vidal Sassoon is more than just a hairdresser-...
441,Decoding Deepak,2012,Gotham Chopra,Deepak Chopra,Gotham Chopra,None,None,Documentary,None,None,5.5,124,10000.0,83,"Deepak Chopra's son, Gotham, spends a year tra..."
442,Theo Who Lived,2016,David Schisgall,Theo Padnos,None,None,None,Documentary,None,None,6.8,111,10000.0,86,A documentary on American journalist Theo Padn...
443,Southern Justice,2006,M.D. Selig,M.D. Selig,Michael Childers,Lisa Robert,Rico Cymone,Action,Adventure,Thriller,3.1,126,140000.0,96,"M.D. Selig's feature thriller, SOUTHERN JUSTIC..."

## Query using Where statement

In [21]:
conn = sqlite3.connect(db_path)

#Query the database to get all data from table 'kaggle_movie'
query = "SELECT * FROM kaggle_movie Where year >= '2016'"

kaggle_movie_2016 = pd.read_sql(query, conn)

conn.close()

In [22]:
kaggle_movie_2016

,movies,year,director,star_1,star_2,star_3,star_4,genre_1,genre_2,genre_3,rating,votes,gross,runtime,description
0,The Hitman's Bodyguard,2017,Patrick Hughes,Ryan Reynolds,Samuel L. Jackson,Gary Oldman,Elodie Yung,Action,Comedy,Crime,6.9,205979,75470000.0,118,"The world's top bodyguard gets a new client, a..."
1,Don't Breathe,2016,Fede Alvarez,Stephen Lang,Jane Levy,Dylan Minnette,Daniel Zovatto,Crime,Horror,Thriller,7.1,237601,89220000.0,88,"Hoping to walk away with a massive fortune, a ..."
2,Escape Room,2019,Adam Robitel,Taylor Russell,Logan Miller,Jay Ellis,Tyler Labine,Action,Adventure,Horror,6.4,99351,57010000.0,99,Six strangers find themselves in a maze of dea...
3,Jumanji: Welcome to the Jungle,2017,Jake Kasdan,Dwayne Johnson,Karen Gillan,Kevin Hart,Jack Black,Action,Adventure,Comedy,6.9,337900,404520000.0,119,Four teenagers are sucked into a magical video...
4,It,2017,Andy Muschietti,Bill SkarsgÃ¥rd,Jaeden Martell,Finn Wolfhard,Sophia Lillis,Horror,None,None,7.3,480607,327480000.0,135,"In the summer of 1989, a group of bullied kids..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,The Final Year,2017,Greg Barker,Ben Rhodes,Samantha Power,John Kerry,Susan Rice,Documentary,None,None,6.4,3191,190000.0,89,A chronicle of the Barack Obama administration...
124,Red Trees,2017,Marina Willer,Alfred Willer,Tim Pigott-Smith,Flora Fanelli,Alfie Watson,Documentary,None,None,6.4,136,10000.0,87,Traces a family's journey as one of only twelv...
125,Restless Creature: Wendy Whelan,2016,"Linda Saffire, Adam Schlesinger",Peter Martins,David Prottas,Wendy Whelan,None,Documentary,None,None,7.1,361,130000.0,90,Documentary on the great American Ballerina We...
126,Facing Darkness,2017,Arthur Rasco,Franklin Graham,Kent Brantly,Amber Brantly,Writebol Nancy,Documentary,Drama,None,7.3,88,560000.0,93,A Christian relief organization is met with th...
127,Theo Who Lived,2016,David Schisgall,Theo Padnos,None,None,None,Documentary,None,None,6.8,111,10000.0,86,A documentary on American journalist Theo Padn...

## Query Unique record

In [23]:
conn = sqlite3.connect(db_path)

#Query the database to get all data from table 'kaggle_movie'
query = "SELECT DISTINCT movies FROM kaggle_movie"

kaggle_unique_movie = pd.read_sql(query, conn)

conn.close()

In [24]:
kaggle_unique_movie

                                                movies
0                               The Hitman's Bodyguard
1                                        Jurassic Park
2                                        Don't Breathe
3    The Lord of the Rings: The Fellowship of the Ring
4                                          Escape Room
..                                                 ...
438                                 Louder Than a Bomb
439                           Vidal Sassoon: The Movie
440                                    Decoding Deepak
441                                     Theo Who Lived
442                                   Southern Justice

[443 rows x 1 columns]